# Generated by Django 3.0.6 on 2021-03-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='identifier_exists',
            field=models.CharField(max_length=32),
        ),
    ]
